version: "3.8"

services:
  backend:
    build: .
    container_name: drone-lite

    ports:
      - "8000:8000"

    restart: unless-stopped

    # keep RAM usage low
    mem_limit: 800m
    cpus: 1.5

    environment:
      - PYTHONUNBUFFERED=1